set relativenumber

noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

noremap <Leader>s :update<CR>
noremap <Leader>vr :source $MYVIMRC<CR>

set laststatus=2

syntax enable

set noswapfile
set nobackup

filetype plugin indent on

set nowrap
